### ISSUE TITLE
Missing blog posts

### ISSUE THREAD

**Issue by jakobnissen** [BioJulia/posts#18]
The old BioJulia blog had at least three blog posts:
1. The comparison between Seq and BioJulia
2. An introduciton to Automa
3. What scientists should know about hardware to write fast code

Post 1 should be included on the new website because I like it.
Post 2 is just a worse version of the v1 Automa documentation - so let's just not upload that.
Post 3 is an outdated version of https://viralinstruction.com/posts/hardware/ - I'm fine with linking to that page to restore the post, but I don't think it's really about BioJulia as such.

Anyway, post 1 should be restored.

**Comment by jakobnissen** [comment]
I can add it when I have time, but it looks like the original blog post was entirely in HTML and the source is lost :fearful:

**Comment by kescobo** [comment]
Just for visibility in case anyone comes across this later - the source isn't lost, I [tagged a release](https://github.com/BioJulia/biojulia.github.io/releases/tag/v0.1) of this repo before I shifted to Xranklin, and the post [is here](https://github.com/BioJulia/biojulia.github.io/tree/65f44bc83d6b91863fb85afacb4c2b20e409ac0d/post/seq-lang)

**Comment by edmundmiller** [comment]
> Just for visibility in case anyone comes across this later - the source isn't lost, I [tagged a release](https://github.com/BioJulia/biojulia.github.io/releases/tag/v0.1) of this repo before I shifted to Xranklin, and the post [is here](https://github.com/BioJulia/biojulia.github.io/tree/65f44bc83d6b91863fb85afacb4c2b20e409ac0d/post/seq-lang)

That's where I've been pulling them from! 

I thought @jakobnissen was referring to the original markdown files that were used to create the html.

**Comment by kescobo** [comment]
Is there any reason not to merge this?

**Comment by edmundmiller** [comment]
Nope, might need to be iterated on/move the hardware post to md, but those can be done in follow-up, might as well get these back out there!

**Comment by edmundmiller** [comment]
- [ ] #25 
- [ ] #26 
- [ ] #27 
- [ ] #28
