### ISSUE TITLE
Link to Documentation

### ISSUE THREAD

**Issue by joelselvaraj** [BioJulia/posts#2]
The documentation in [http://biojulia.net/Bio.jl/stable/](http://biojulia.net/Bio.jl/stable/) is not linked in the top navigation bar or anywhere in the main site [http://biojulia.net](http://biojulia.net).

**Comment by TransGirlCodes** [comment]
On the main site, every package maintained by BioJulia is going to have it's own small page with links to the documentation as well as the github and so on: http://biojulia.net/packages/. You will see I have not yet finished it, as the decomposition of Bio.jl into smaller packages has yet to be finished (We are, I would estimate, just over half way there).

**Comment by joelselvaraj** [comment]
Nice to know. Hope its finished soon as the site and docs seems to be little messy.

**Comment by TransGirlCodes** [comment]
The docs on other packages, for example biojulia.net/BioSequences.jl or biojulia.net/BioSymbols.jl we generated using mkdocs, are currently perhaps better than the page generated for Bio.jl. Bio.jl is currently different for historic reasons: Bio.jl also housed the "main page" before we started this repo for a github organisation page.

**Comment by joelselvaraj** [comment]
Ok. The docs on other packages looks good as you mentioned. It would also be nice if the theme for Bio.jl docs and individual package's docs are same. Might be an obvious suggestion. Just said.

**Comment by kescobo** [comment]
This is now being worked on in BioJuliaDocs, see https://github.com/orgs/BioJulia/discussions/10
