### ISSUE TITLE
Verify the "biojulia.net" domain with the "BioJulia" GitHub organization

### ISSUE THREAD

**Issue by DilumAluthge** [BioJulia/posts#7]
I notice that currently, the `biojulia.net` domain is not verified with the "BioJulia" GitHub organization.

Verifying the domain will add a green "Verified" badge on https://github.com/BioJulia, which may help increase people's level of perceived trust in the BioJulia GitHub organization.

The process is straightforward: https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams/verifying-your-organizations-domain

Would it be possible to verify the `biojulia.net` domain?

cc: @BenJWard

**Comment by DilumAluthge** [comment]
Bump @BenJWard

**Comment by TransGirlCodes** [comment]
@DilumAluthge I've configured the DNS, I'll just let it wait for the duration of a tea break to update. I know it says 72 hours but it's normally way faster than that.

**Comment by DilumAluthge** [comment]
Any luck?

**Comment by TransGirlCodes** [comment]
All done, I had some issues as you need to do something slightly different for my domain name provider than what github tells you to, but I found an FAQ that set it right.
