### ISSUE TITLE
Convert to Franklin.jl?

### ISSUE THREAD

**Issue by kescobo** [BioJulia/posts#8]
This would be a bit of a heavy lift, I think, but it might be worth converting to a [Franklin.jl](https://franklinjl.org/) site, so that we can do everything in julia. And @tlienart tends to be super helpful working out bugs.

**Comment by CiaranOMara** [comment]
Note: A GitHub workflow example of a Franklin.jl deployment. https://github.com/JuliaLang/www.julialang.org/blob/main/.github/workflows/deploy.yml

**Comment by tlienart** [comment]
As a note I had started working on this myself some time ago then put it on the back burner but could resuscitate it if there is interest from devs here. Most of it is Academic template which is now mostly supported in Franklin. A couple of things that would probably require a bit of figuring out are:

* dark mode (seems to be mostly a toggle in javascript with a cookie so should be mostly ok)
* search (I'm not exactly sure what search this is but it's not Lunr, it's probably also one of those javascript libs)

I could get you guys started if you wanted to but I'll need help (e.g.: tracking down minor issues & checking for the two points above)

**Comment by kescobo** [comment]
>Most of it is Academic template which is now mostly supported in Franklin

Amazing! where's that development happening?

>I could get you guys started if you wanted to but I'll need help (e.g.: tracking down minor issues & checking for the two points above)

Thanks so much! I'd be happy to help out with this. Regarding search - I don't know that we actually care, as long as we have something functional? Re: Dark mode - There's an example of this in https://github.com/fredrikekre/fredrikekre.se (see https://fredrikekre.se/)

**Comment by tlienart** [comment]
> where's that development happening?

https://github.com/tlienart/ft-academic-resume

> Re: Dark mode - There's an example of this in https://github.com/fredrikekre/fredrikekre.se (see https://fredrikekre.se/)

yes but this typically requires a bit of care (esp around CSS) so I think it would be the kind of stuff where I'd let you guys do it and help out if you think there are Franklin-specific things that can be done to help :)

**Comment by kescobo** [comment]
@tlienart You said you already made some progress on this - is there something I can do to help? I can try to move the content files over to that `academic` franklin template, but if you've already started, I don't want to reinvent the wheel.

Realistically, I'm not going to put much effort into this until the summer, so there's zero rush, just curious.

**Comment by tlienart** [comment]
I should probably re-start this if you folks are keen, I can do some of the early work and you can do the grunt work of adding blog posts and fine tuning :) 

summer sounds good! ping me if I forget but I should have the time (maybe not immediately but soon)

**Comment by kescobo** [comment]
Mostly done in #16, but having some deployment issues https://github.com/tlienart/Xranklin.jl/issues/252

**Comment by kescobo** [comment]
A lot of work still left to do, but I'm going to close this in favor of new issues on the current site :tada:
